language: php

# dist: trusty

php:
- 5.6
- 7.0
- 7.1
- hhvm

install:
- phpenv rehash
- composer require "satooshi/php-coveralls" "^1" --dev --no-update
- composer install --no-interaction

script:
- phpunit -c phpunit.xml.dist

after_success:
- php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
  - php: "hhvm"
  - php: "5.6"

cache:
  apt: true
  directories:
  - vendor

notifications:
  email:
    on_success: change # default: always
    on_failure: change # default: always
  slack:
    secure: G/7MNT2ZQirPcxX4ui1qn7mfDi29FPIY1ThN4c+KMp5IMLoFtHmrs+3hdCXLQC4mYkWrqLQVQpqRZb92qemZAbRpyaV+1g6IDFzunia95aF2eDRD73TQCNDrKkxhBi69FGo3ToOiB1wTtX/WYLFfkfOmFI43Wu+5fTmvH2mOtIk=
