language: php

php:
- 5.6
- 7.0
- hhvm

before_script:
- phpenv rehash
- composer update --no-interaction
- mkdir -p build/logs

script:
- phpunit -c phpunit.xml.dist

after_success:
- php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
  - php: "hhvm"
  - php: "5.6"

cache:
- vendor
