language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - phpenv rehash
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

cache:
  - vendor
